--------------------------------------------------------
-- Archivo creado  - viernes-agosto-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCIDENTES
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."ACCIDENTES" 
   (	"IDACCIDENTE" NUMBER, 
	"FECHA" VARCHAR2(10 BYTE), 
	"HORA" VARCHAR2(10 BYTE), 
	"SUCESO" VARCHAR2(500 BYTE), 
	"LUGAR" VARCHAR2(100 BYTE), 
	"CLIENTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALTERNATIVAS
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."ALTERNATIVAS" 
   (	"ID_A" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"VALOR1" CHAR(1 BYTE), 
	"VALOR2" NUMBER(10,0), 
	"PREGUNTAS_ID_P" NUMBER(10,0), 
	"ESTUDIANTE_ESTUDIANTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASESORIAS
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."ASESORIAS" 
   (	"IDASESORIA" NUMBER, 
	"DETALLE" VARCHAR2(500 BYTE), 
	"GESTION" VARCHAR2(500 BYTE), 
	"PROPUESTAS" VARCHAR2(500 BYTE), 
	"FECHA" VARCHAR2(10 BYTE), 
	"ESPECIAL" VARCHAR2(10 BYTE), 
	"VISITAS_IDVISITA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAPACITACIONES
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."CAPACITACIONES" 
   (	"IDCAPACITACION" NUMBER, 
	"FECHA" VARCHAR2(10 BYTE), 
	"HORA" VARCHAR2(10 BYTE), 
	"NUMASISTENTES" NUMBER, 
	"VISITAS_IDVISITA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHEQUEO
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."CHEQUEO" 
   (	"IDCHEQUEO" NUMBER, 
	"DETALLE" VARCHAR2(10 BYTE), 
	"ESTADO" VARCHAR2(5 BYTE), 
	"VISITAS_IDVISITA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."CLIENTE" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELEFONO" NUMBER, 
	"CORREOELECTRONICO" VARCHAR2(50 BYTE), 
	"RUBRO" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURSO
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."CURSO" 
   (	"CURSO" VARCHAR2(20 BYTE), 
	"CODIGO" VARCHAR2(10 BYTE), 
	"DIA" VARCHAR2(10 BYTE), 
	"USUARIO_CI" VARCHAR2(15 BYTE), 
	"LOCACION_CODIG" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."EMPLEADO" 
   (	"IDEMPLEADO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ESPECIALIDAD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."ESTUDIANTE" 
   (	"NOMBREE" VARCHAR2(15 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"PROGRAMA" VARCHAR2(20 BYTE), 
	"VALOR2" NUMBER(10,0), 
	"TEST_ID_TEST" NUMBER(10,0), 
	"ESTUDIANTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCACION
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."LOCACION" 
   (	"REGION" VARCHAR2(15 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(20 BYTE), 
	"CODIG" NUMBER, 
	"USUARIO_CI" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEJORAS
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."MEJORAS" 
   (	"IDMEJORA" NUMBER, 
	"FECHA" VARCHAR2(10 BYTE), 
	"MOTIVO" VARCHAR2(500 BYTE), 
	"ACTIVIDADES" VARCHAR2(500 BYTE), 
	"ESTADO" VARCHAR2(5 BYTE), 
	"CLIENTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGOS
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."PAGOS" 
   (	"IDPAGO" NUMBER, 
	"MESANIO" VARCHAR2(11 BYTE), 
	"MONTOREGULAR" NUMBER, 
	"MONTOADICIONALES" NUMBER, 
	"CLIENTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAS
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."PREGUNTAS" 
   (	"ID_P" NUMBER(10,0), 
	"ENUNCIADO" VARCHAR2(20 BYTE), 
	"PUNTAJE" NUMBER(10,0), 
	"TEST_ID_TEST" NUMBER(10,0), 
	"ESTUDIANTE_ESTUDIANTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."TEST" 
   (	"ID_TEST" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"PROGRAMA" VARCHAR2(20 BYTE), 
	"UNIDAD" NUMBER(10,0), 
	"AUTOR" VARCHAR2(20 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."USUARIO" 
   (	"N0MBRE" VARCHAR2(15 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"CI" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VISITAS
--------------------------------------------------------

  CREATE TABLE "ALUMNO"."VISITAS" 
   (	"IDVISITA" NUMBER, 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"CIUDAD" VARCHAR2(50 BYTE), 
	"FECHA" VARCHAR2(10 BYTE), 
	"RESUMEN" VARCHAR2(500 BYTE), 
	"OBSERVACIONES" VARCHAR2(500 BYTE), 
	"CLIENTE_ID" NUMBER, 
	"EMPLEADO_IDEMPLEADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CHEQUEO
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."CHEQUEO" ADD CONSTRAINT "CHEQUEO_PK" PRIMARY KEY ("IDCHEQUEO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."CHEQUEO" MODIFY ("IDCHEQUEO" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CHEQUEO" MODIFY ("DETALLE" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CHEQUEO" MODIFY ("ESTADO" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CHEQUEO" MODIFY ("VISITAS_IDVISITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCACION
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."LOCACION" ADD CONSTRAINT "LOCACION_PK" PRIMARY KEY ("CODIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."LOCACION" MODIFY ("CODIG" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."LOCACION" MODIFY ("USUARIO_CI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAPACITACIONES
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."CAPACITACIONES" ADD CONSTRAINT "CAPACITACIONES_PK" PRIMARY KEY ("IDCAPACITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."CAPACITACIONES" MODIFY ("IDCAPACITACION" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CAPACITACIONES" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CAPACITACIONES" MODIFY ("HORA" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CAPACITACIONES" MODIFY ("VISITAS_IDVISITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASESORIAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ASESORIAS" ADD CONSTRAINT "ASESORIAS_PK" PRIMARY KEY ("IDASESORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."ASESORIAS" MODIFY ("IDASESORIA" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ASESORIAS" MODIFY ("GESTION" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ASESORIAS" MODIFY ("VISITAS_IDVISITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCIDENTES
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ACCIDENTES" ADD CONSTRAINT "ACCIDENTES_PK" PRIMARY KEY ("IDACCIDENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."ACCIDENTES" MODIFY ("IDACCIDENTE" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ACCIDENTES" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ACCIDENTES" MODIFY ("HORA" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ACCIDENTES" MODIFY ("SUCESO" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ACCIDENTES" MODIFY ("LUGAR" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ACCIDENTES" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CURSO
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."CURSO" ADD CONSTRAINT "CURSO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."CURSO" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CURSO" MODIFY ("USUARIO_CI" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CURSO" MODIFY ("LOCACION_CODIG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("IDEMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."EMPLEADO" MODIFY ("IDEMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_PK" PRIMARY KEY ("ESTUDIANTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."ESTUDIANTE" MODIFY ("TEST_ID_TEST" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ESTUDIANTE" MODIFY ("ESTUDIANTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."PREGUNTAS" ADD CONSTRAINT "PREGUNTAS_PK" PRIMARY KEY ("ID_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."PREGUNTAS" MODIFY ("ID_P" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."PREGUNTAS" MODIFY ("TEST_ID_TEST" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."PREGUNTAS" MODIFY ("ESTUDIANTE_ESTUDIANTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."TEST" MODIFY ("ID_TEST" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("ID_TEST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."USUARIO" MODIFY ("CI" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("CI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEJORAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."MEJORAS" ADD CONSTRAINT "MEJORAS_PK" PRIMARY KEY ("IDMEJORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."MEJORAS" MODIFY ("IDMEJORA" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."MEJORAS" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."PAGOS" ADD CONSTRAINT "PAGOS_PK" PRIMARY KEY ("IDPAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."PAGOS" MODIFY ("IDPAGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VISITAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."VISITAS" MODIFY ("IDVISITA" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."VISITAS" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."VISITAS" MODIFY ("EMPLEADO_IDEMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."VISITAS" ADD CONSTRAINT "VISITAS_PK" PRIMARY KEY ("IDVISITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALTERNATIVAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ALTERNATIVAS" ADD CONSTRAINT "ALTERNATIVAS_PK" PRIMARY KEY ("ID_A", "PREGUNTAS_ID_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALUMNO"."ALTERNATIVAS" MODIFY ("ID_A" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ALTERNATIVAS" MODIFY ("PREGUNTAS_ID_P" NOT NULL ENABLE);
 
  ALTER TABLE "ALUMNO"."ALTERNATIVAS" MODIFY ("ESTUDIANTE_ESTUDIANTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCIDENTES
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ACCIDENTES" ADD CONSTRAINT "ACCIDENTES_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "ALUMNO"."CLIENTE" ("ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALTERNATIVAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ALTERNATIVAS" ADD CONSTRAINT "ALTERNATIVAS_ESTUDIANTE_FK" FOREIGN KEY ("ESTUDIANTE_ESTUDIANTE_ID")
	  REFERENCES "ALUMNO"."ESTUDIANTE" ("ESTUDIANTE_ID") ENABLE;
 
  ALTER TABLE "ALUMNO"."ALTERNATIVAS" ADD CONSTRAINT "ALTERNATIVAS_PREGUNTAS_FK" FOREIGN KEY ("PREGUNTAS_ID_P")
	  REFERENCES "ALUMNO"."PREGUNTAS" ("ID_P") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASESORIAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ASESORIAS" ADD CONSTRAINT "ASESORIAS_VISITAS_FK" FOREIGN KEY ("VISITAS_IDVISITA")
	  REFERENCES "ALUMNO"."VISITAS" ("IDVISITA") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAPACITACIONES
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."CAPACITACIONES" ADD CONSTRAINT "CAPACITACIONES_VISITAS_FK" FOREIGN KEY ("VISITAS_IDVISITA")
	  REFERENCES "ALUMNO"."VISITAS" ("IDVISITA") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHEQUEO
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."CHEQUEO" ADD CONSTRAINT "CHEQUEO_VISITAS_FK" FOREIGN KEY ("VISITAS_IDVISITA")
	  REFERENCES "ALUMNO"."VISITAS" ("IDVISITA") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURSO
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."CURSO" ADD CONSTRAINT "CURSO_LOCACION_FK" FOREIGN KEY ("LOCACION_CODIG")
	  REFERENCES "ALUMNO"."LOCACION" ("CODIG") ENABLE;
 
  ALTER TABLE "ALUMNO"."CURSO" ADD CONSTRAINT "CURSO_USUARIO_FK" FOREIGN KEY ("USUARIO_CI")
	  REFERENCES "ALUMNO"."USUARIO" ("CI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_TEST_FK" FOREIGN KEY ("TEST_ID_TEST")
	  REFERENCES "ALUMNO"."TEST" ("ID_TEST") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCACION
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."LOCACION" ADD CONSTRAINT "LOCACION_USUARIO_FK" FOREIGN KEY ("USUARIO_CI")
	  REFERENCES "ALUMNO"."USUARIO" ("CI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEJORAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."MEJORAS" ADD CONSTRAINT "MEJORAS_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "ALUMNO"."CLIENTE" ("ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."PREGUNTAS" ADD CONSTRAINT "PREGUNTAS_ESTUDIANTE_FK" FOREIGN KEY ("ESTUDIANTE_ESTUDIANTE_ID")
	  REFERENCES "ALUMNO"."ESTUDIANTE" ("ESTUDIANTE_ID") ENABLE;
 
  ALTER TABLE "ALUMNO"."PREGUNTAS" ADD CONSTRAINT "PREGUNTAS_TEST_FK" FOREIGN KEY ("TEST_ID_TEST")
	  REFERENCES "ALUMNO"."TEST" ("ID_TEST") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VISITAS
--------------------------------------------------------

  ALTER TABLE "ALUMNO"."VISITAS" ADD CONSTRAINT "VISITAS_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "ALUMNO"."CLIENTE" ("ID") DISABLE;
 
  ALTER TABLE "ALUMNO"."VISITAS" ADD CONSTRAINT "VISITAS_EMPLEADO_FK" FOREIGN KEY ("EMPLEADO_IDEMPLEADO")
	  REFERENCES "ALUMNO"."EMPLEADO" ("IDEMPLEADO") DISABLE;
